### ISSUE TITLE
about environment

### ISSUE THREAD

**Issue by KANGXI123456** [felixcheng97/IICNet#3]
Thank you for your great work!!!
I have a question about the environment, do you use the cuda10.2?
I encountered this problem when configuring the environment
![2022-03-14 11-16-47 的屏幕截图](https://user-images.githubusercontent.com/87471239/158099052-461c4420-5711-4e37-8956-2ef4eb3fb8af.png)
the pythorch and torchvision unable to be installed
do you have an environment.txt so that I can    pip install  environment.txt
thank you very much!

**Comment by felixcheng97** [comment]
Thanks for your interest in our work. 

All the experiments are run on the Linux machine with the following:
- Ubuntu 18.04.3
- NVIDIA-SMI 440.33.01
- Driver Version: 440.33.01
- CUDA Version: 10.2
- GPU: GeForce RTX 2080 Ti

Please copy and paste the following to the file named "requirements.txt". 

absl-py==0.15.0
blessings==1.7
cachetools==4.2.4
certifi==2020.6.20
chardet==4.0.0
cycler==0.10.0
decorator==5.1.1
future==0.18.2
google-auth==1.23.0
google-auth-oauthlib==0.4.1
gpustat==0.6.0
grpcio==1.41.1
idna==2.10
imageio==2.9.0
importlib-metadata==2.1.3
joblib==0.14.1
kiwisolver==1.1.0
Markdown==3.2.2
matplotlib==3.0.3
networkx==2.4
numpy==1.18.5
nvidia-ml-py3==7.352.0
oauthlib==3.1.0
opencv-python==4.4.0.42
Pillow==7.2.0
protobuf==3.19.4
psutil==5.9.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pyparsing==2.4.7
python-dateutil==2.8.2
PyWavelets==1.1.1
PyYAML==5.3.1
requests==2.25.1
requests-oauthlib==1.3.1
rsa==4.7.2
scikit-image==0.15.0
scikit-learn==0.22.2.post1
scipy==1.4.1
six==1.16.0
tensorboard==2.4.1
tensorboard-plugin-wit==1.8.1
torch==1.5.1
torchvision==0.6.1
urllib3==1.26.8
Werkzeug==1.0.1
zipp==1.2.0

Go to the directory containing the "requirements.txt" file and run the following:
- conda create --name iic python=3.5
- conda activate iic
- pip install --upgrade pip
- pip install -r requirements.txt

Hope these help.

**Comment by KANGXI123456** [comment]
Thanks you for your reply, I have successfully trained and tested the first task, but I encountered another question:
![2022-03-17 10-26-31 的屏幕截图](https://user-images.githubusercontent.com/87471239/158724424-7ef7fef2-bedc-49f2-b22b-d79fa0f49215.png)
after the test, I didn't get the embedding image, didn't it generate the embedding image in testing?

and there is a image named 'embedding_frame_prime.png' in folder 'val_sample', is it the embedding image in the process o
![43169882A67ABBE11F48D8AACEA36106](https://user-images.githubusercontent.com/87471239/158725528-59d59cbf-f3ab-40ca-b1b7-99a59ab2c61e.jpg)
f validation?

**Comment by KANGXI123456** [comment]
Thanks you for your reply, I have successfully trained and tested the first task, but I encountered another question: after the test, I didn't get the embedding image, didn't it generate the embedding image in testing?
![2022-03-17 10-26-31 的屏幕截图](https://user-images.githubusercontent.com/87471239/158725932-1fbf6ae2-2ee2-43f4-b909-75ac41fed01a.png)


and there is a image named 'embedding_frame_prime.png' in folder 'val_sample', is it the embedding image in the process of validation?
![43169882A67ABBE11F48D8AACEA36106](https://user-images.githubusercontent.com/87471239/158725963-18543a2e-fb80-4bcf-b2fd-411b76583867.jpg)

**Comment by felixcheng97** [comment]
Thanks for your question.

For your first question, yes, it should be generated during testing. I have corrected the test.py to save the embedding image as well. Please kindly check the updated version of the code.

For your second question, yes, 'embedding_frame_prime.png' (embedding_frame after quantization) is the embedding image in the process of validation.

Hope these help.

**Comment by felixcheng97** [comment]
I am closing this issue since the problem has been resolved.
